name: Create GKE using Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ././deploy/kubernetes/terraform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Export SA Key for Terraform Backend
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/home/mkljestan/actions-runner/gcp_sa.json

      # reqired for terraform on self-hosted runners
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: |
          terraform init
      
      - name: Terraform Format
        run: |
          terraform fmt

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve