name: Terraform Destroy

on:
  workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy/kubernetes/terraform
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

      # reqired for terraform on self-hosted runners
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform Init
      run: |
        terraform init 

    - name: Terraform Destroy
      run: |
        terraform destroy 
      env:
        TF_VAR_service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
